### ISSUE TITLE
the view key and spend key in the bottom just have `Generating...` and dont dispay any values

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/paper-turtle#14]

**Comment by Sajo8** [comment]
also give me back my mnemonic seed

**Comment by Sajo8** [comment]
also i cant input my seed anymore to restore my private keys from it, wth whered that go

**Comment by Watt3r** [comment]
Are you using the latest version?

**Comment by Watt3r** [comment]
https://github.com/turtlecoin/turtlecoin.lol/pull/65

**Comment by Sajo8** [comment]
👍
