### ISSUE TITLE
there's no way for me to input my mnemonic seed and get back my private spend and view keys

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/paper-turtle#15]

**Comment by Watt3r** [comment]
Pull the repo again, this was fixed

**Comment by Sajo8** [comment]
im using turtlecoin.lol/wallet i shouldnt have to pull the repo

**Comment by RocksteadyTC** [comment]
Does this issue persist?

**Comment by Watt3r** [comment]
No

**Comment by Watt3r** [comment]
Fixed in https://github.com/turtlecoin/turtlecoin.lol/commit/b848ba6046724492dbeee214b755291e3d8ecb8f

**Comment by RocksteadyTC** [comment]
Thanks watter

**Comment by Sajo8** [comment]
Thanks
